### ISSUE TITLE
This section should be around 300-500 words and the reflection-milestone4.md document should live in your GitHub.com repo in the doc folder.

### ISSUE THREAD

**Issue by christopheralex** [UBC-MDS/spotify-explorer-R#16]

**Comment by christopheralex** [comment]
@jennifer-hoang I think Florenica mentions that we need to have it in both the Repos ? Or is one repo fine ?

**Comment by jennifer-hoang** [comment]
Michelle added it to the python repo as well! 
https://github.com/UBC-MDS/spotify-explorer-py/blob/main/doc/reflection-milestone4.md
